title: Gaspard Bourgeois' Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Discover some of my key projects through their relevant articles.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gaspard Bourgeois # add your name
author-img: gaspard-bourgeois.jpg # add your photo
about-author: I am an early robotics engineer coming from Arts et Métiers school. I am eager to develop and share my technical knowledge collected along some of those experiences.  # add description
social-twitter: # add your Twitter handle
social-facebook: "gaspard.bourgeois.35"# add your Facebook handle
social-github: "Gaspard-Bourgeois/gaspard-bourgeois.github.io/" # add your Github handle
social-linkedin: "gaspard-bourgeois-89559a12b" # add your Linkedin handle
social-email: "gaspard.github.io@free.fr"# add your Email address
location: "Paris, France"


# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
