title: Gaspard Bourgeois' Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Gaspard Bourgeois # add your name
author-img: gaspard-bourgeois.jpg # add your photo
about-author: I am a last year engineer student in Arts et Métiers School. Always curious to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: "gaspard.bourgeois.35"# add your Facebook handle
social-github: "Gaspard-Bourgeois/gaspard-bourgeois.github.io/" # add your Github handle
social-linkedin: "gaspard-bourgeois-89559a12b" # add your Linkedin handle
social-email: "gaspard.github.io@free.fr"# add your Email address
location: "Paris, France"


# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
